server {
  listen ${PORT};
  listen [::]:${PORT};
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /weboc/ {
    proxy_pass https://weboc.gov.pk/;
    proxy_set_header Host weboc.gov.pk;
    proxy_set_header Origin "";
    proxy_set_header Referer "";
    proxy_ssl_server_name on;

    proxy_hide_header X-Frame-Options;
    proxy_hide_header Content-Security-Policy;
    proxy_hide_header Permissions-Policy;
    proxy_hide_header Permissions-Policy-Report-Only;
  }

  location /weboc-www/ {
    proxy_pass https://www.weboc.gov.pk/;
    proxy_set_header Host www.weboc.gov.pk;
    proxy_set_header Origin "";
    proxy_set_header Referer "";
    proxy_ssl_server_name on;

    proxy_hide_header X-Frame-Options;
    proxy_hide_header Content-Security-Policy;
    proxy_hide_header Permissions-Policy;
    proxy_hide_header Permissions-Policy-Report-Only;
  }

  location = /WebResource.axd {
    proxy_pass https://weboc.gov.pk/WebResource.axd;
    proxy_set_header Host weboc.gov.pk;
    proxy_ssl_server_name on;

    proxy_hide_header X-Frame-Options;
    proxy_hide_header Content-Security-Policy;
  }

  location = /ScriptResource.axd {
    proxy_pass https://weboc.gov.pk/ScriptResource.axd;
    proxy_set_header Host weboc.gov.pk;
    proxy_ssl_server_name on;

    proxy_hide_header X-Frame-Options;
    proxy_hide_header Content-Security-Policy;
  }
}
